# node data extracted with extract_node_data
blender_node_data = {
    "CombineXYZ": {
        "inputs": [
            {"default": 0.0, "input_id": 0, "name": "X", "type": "float"},
            {"default": 0.0, "input_id": 1, "name": "Y", "type": "float"},
            {"default": 0.0, "input_id": 2, "name": "Z", "type": "float"},
        ],
        "outputs": {"Vector": {"type": "Vector"}},
        "params": {},
    },
    "Mapping": {
        "inputs": [
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 0,
                "name": "Vector",
                "type": "vector",
            },
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 1,
                "name": "Location",
                "type": "vector",
            },
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 2,
                "name": "Rotation",
                "type": "vector",
            },
            {
                "default": (1.0, 1.0, 1.0),
                "input_id": 3,
                "name": "Scale",
                "type": "vector",
            },
        ],
        "outputs": {"Vector": {"type": "vector"}},
        "params": {
            "vector_type": {
                "default": "POINT",
                "options": ["POINT", "TEXTURE", "VECTOR", "NORMAL"],
                "type": "enum",
            }
        },
    },
    "Math": {
        "inputs": [
            {"default": 0.5, "input_id": 0, "name": "Value", "type": "float"},
            {"default": 0.5, "input_id": 1, "name": "Value", "type": "float"},
            {"default": 0.5, "input_id": 2, "name": "Value", "type": "float"},
        ],
        "outputs": {"Value": {"type": "Value"}},
        "params": {
            "operation": {
                "default": "ADD",
                "options": [
                    "ADD",
                    "SUBTRACT",
                    "MULTIPLY",
                    "DIVIDE",
                    "MULTIPLY_ADD",
                    "POWER",
                    "LOGARITHM",
                    "SQRT",
                    "INVERSE_SQRT",
                    "ABSOLUTE",
                    "EXPONENT",
                    "MINIMUM",
                    "MAXIMUM",
                    "LESS_THAN",
                    "GREATER_THAN",
                    "SIGN",
                    "COMPARE",
                    "SMOOTH_MIN",
                    "SMOOTH_MAX",
                    "ROUND",
                    "FLOOR",
                    "CEIL",
                    "TRUNC",
                    "FRACT",
                    "MODULO",
                    "FLOORED_MODULO",
                    "WRAP",
                    "SNAP",
                    "PINGPONG",
                    "SINE",
                    "COSINE",
                    "TANGENT",
                    "ARCSINE",
                    "ARCCOSINE",
                    "ARCTANGENT",
                    "ARCTAN2",
                    "SINH",
                    "COSH",
                    "TANH",
                    "RADIANS",
                    "DEGREES",
                ],
                "type": "enum",
            },
            "use_clamp": {"default": False, "type": "boolean"},
        },
    },
    "Mix": {
        "inputs": [
            {"default": 0.5, "input_id": 0, "name": "Factor", "type": "float"},
            {
                "default": (0.5, 0.5, 0.5),
                "input_id": 1,
                "name": "Factor",
                "type": "vector",
            },
            {"default": 0.0, "input_id": 2, "name": "A", "type": "float"},
            {"default": 0.0, "input_id": 3, "name": "B", "type": "float"},
            {"default": (0.0, 0.0, 0.0), "input_id": 4, "name": "A", "type": "vector"},
            {"default": (0.0, 0.0, 0.0), "input_id": 5, "name": "B", "type": "vector"},
            {
                "default": (0.5, 0.5, 0.5, 1.0),
                "input_id": 6,
                "name": "A",
                "type": "vector",
            },
            {
                "default": (0.5, 0.5, 0.5, 1.0),
                "input_id": 7,
                "name": "B",
                "type": "vector",
            },
            {"default": (0.0, 0.0, 0.0), "input_id": 8, "name": "A", "type": "vector"},
            {"default": (0.0, 0.0, 0.0), "input_id": 9, "name": "B", "type": "vector"},
        ],
        "outputs": {"Result": {"type": "vector"}},
        "params": {
            "blend_type": {
                "default": "MIX",
                "options": [
                    "MIX",
                    "DARKEN",
                    "MULTIPLY",
                    "BURN",
                    "LIGHTEN",
                    "SCREEN",
                    "DODGE",
                    "ADD",
                    "OVERLAY",
                    "SOFT_LIGHT",
                    "LINEAR_LIGHT",
                    "DIFFERENCE",
                    "EXCLUSION",
                    "SUBTRACT",
                    "DIVIDE",
                    "HUE",
                    "SATURATION",
                    "COLOR",
                    "VALUE",
                ],
                "type": "enum",
            },
            "clamp_factor": {"default": True, "type": "boolean"},
            "clamp_result": {"default": False, "type": "boolean"},
            "data_type": {
                "default": "FLOAT",
                "options": ["FLOAT", "VECTOR", "RGBA", "ROTATION"],
                "type": "enum",
            },
            "factor_mode": {
                "default": "UNIFORM",
                "options": ["UNIFORM", "NON_UNIFORM"],
                "type": "enum",
            },
        },
    },
    "MixRGB": {
        "inputs": [
            {"default": 0.5, "input_id": 0, "name": "Fac", "type": "float"},
            {
                "default": (0.5, 0.5, 0.5, 1.0),
                "input_id": 1,
                "name": "Color1",
                "type": "vector",
            },
            {
                "default": (0.5, 0.5, 0.5, 1.0),
                "input_id": 2,
                "name": "Color2",
                "type": "vector",
            },
        ],
        "outputs": {"Color": {"type": "vector"}},
        "params": {
            "blend_type": {
                "default": "MIX",
                "options": [
                    "MIX",
                    "DARKEN",
                    "MULTIPLY",
                    "BURN",
                    "LIGHTEN",
                    "SCREEN",
                    "DODGE",
                    "ADD",
                    "OVERLAY",
                    "SOFT_LIGHT",
                    "LINEAR_LIGHT",
                    "DIFFERENCE",
                    "EXCLUSION",
                    "SUBTRACT",
                    "DIVIDE",
                    "HUE",
                    "SATURATION",
                    "COLOR",
                    "VALUE",
                ],
                "type": "enum",
            },
            "use_alpha": {"default": False, "type": "boolean"},
            "use_clamp": {"default": False, "type": "boolean"},
        },
    },
    "SeparateXYZ": {
        "inputs": [
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 0,
                "name": "Vector",
                "type": "vector",
            }
        ],
        "outputs": {
            "X": {"type": "vector"},
            "Y": {"type": "vector"},
            "Z": {"type": "vector"},
        },
        "params": {},
    },
    "TexBrick": {
        "inputs": [
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 0,
                "name": "Vector",
                "type": "vector",
            },
            {
                "default": (
                    0.800000011920929,
                    0.800000011920929,
                    0.800000011920929,
                    1.0,
                ),
                "input_id": 1,
                "name": "Color1",
                "type": "vector",
            },
            {
                "default": (
                    0.20000000298023224,
                    0.20000000298023224,
                    0.20000000298023224,
                    1.0,
                ),
                "input_id": 2,
                "name": "Color2",
                "type": "vector",
            },
            {
                "default": (0.0, 0.0, 0.0, 1.0),
                "input_id": 3,
                "name": "Mortar",
                "type": "vector",
            },
            {"default": 5.0, "input_id": 4, "name": "Scale", "type": "float"},
            {
                "default": 0.019999999552965164,
                "input_id": 5,
                "name": "Mortar Size",
                "type": "float",
            },
            {
                "default": 0.10000000149011612,
                "input_id": 6,
                "name": "Mortar Smooth",
                "type": "float",
            },
            {"default": 0.0, "input_id": 7, "name": "Bias", "type": "float"},
            {"default": 0.5, "input_id": 8, "name": "Brick Width", "type": "float"},
            {"default": 0.25, "input_id": 9, "name": "Row Height", "type": "float"},
        ],
        "outputs": {"Color": {"type": "Color"}, "Fac": {"type": "Fac"}},
        "params": {
            "offset": {"default": 0.5, "max": 1.0, "min": 0.0, "type": "float"},
            "offset_frequency": {"default": 2, "max": 99, "min": 1, "type": "int"},
            "squash": {"default": 1.0, "max": 99.0, "min": 0.0, "type": "float"},
            "squash_frequency": {"default": 2, "max": 99, "min": 1, "type": "int"},
        },
    },
    "TexChecker": {
        "inputs": [
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 0,
                "name": "Vector",
                "type": "vector",
            },
            {
                "default": (
                    0.800000011920929,
                    0.800000011920929,
                    0.800000011920929,
                    1.0,
                ),
                "input_id": 1,
                "name": "Color1",
                "type": "vector",
            },
            {
                "default": (
                    0.20000000298023224,
                    0.20000000298023224,
                    0.20000000298023224,
                    1.0,
                ),
                "input_id": 2,
                "name": "Color2",
                "type": "vector",
            },
            {"default": 5.0, "input_id": 3, "name": "Scale", "type": "float"},
        ],
        "outputs": {"Color": {"type": "Color"}, "Fac": {"type": "Fac"}},
        "params": {},
    },
    "TexCoord": {
        "inputs": [],
        "outputs": {
            "Camera": {"type": "Camera"},
            "Generated": {"type": "Generated"},
            "Normal": {"type": "Normal"},
            "Object": {"type": "Object"},
            "Reflection": {"type": "Reflection"},
            "UV": {"type": "UV"},
            "Window": {"type": "Window"},
        },
        "params": {"from_instancer": {"default": False, "type": "boolean"}},
    },
    "TexGabor": {
        "inputs": [
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 0,
                "name": "Vector",
                "type": "vector",
            },
            {"default": 5.0, "input_id": 1, "name": "Scale", "type": "float"},
            {"default": 2.0, "input_id": 2, "name": "Frequency", "type": "float"},
            {"default": 1.0, "input_id": 3, "name": "Anisotropy", "type": "float"},
            {
                "default": 0.7853981852531433,
                "input_id": 4,
                "name": "Orientation",
                "type": "float",
            },
            {
                "default": (1.4142135381698608, 1.4142135381698608, 0.0),
                "input_id": 5,
                "name": "Orientation",
                "type": "vector",
            },
        ],
        "outputs": {
            "Intensity": {"type": "vector"},
            "Phase": {"type": "vector"},
            "Value": {"type": "vector"},
        },
        "params": {"gabor_type": {"default": "2D", "options": ["2D", "3D"], "type": "enum"}},
    },
    "TexGradient": {
        "inputs": [
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 0,
                "name": "Vector",
                "type": "vector",
            }
        ],
        "outputs": {"Color": {"type": "vector"}, "Fac": {"type": "vector"}},
        "params": {
            "gradient_type": {
                "default": "LINEAR",
                "options": [
                    "LINEAR",
                    "QUADRATIC",
                    "EASING",
                    "DIAGONAL",
                    "SPHERICAL",
                    "QUADRATIC_SPHERE",
                    "RADIAL",
                ],
                "type": "enum",
            }
        },
    },
    "TexNoise": {
        "inputs": [
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 0,
                "name": "Vector",
                "type": "vector",
            },
            {"default": 0.0, "input_id": 1, "name": "W", "type": "float"},
            {"default": 5.0, "input_id": 2, "name": "Scale", "type": "float"},
            {"default": 2.0, "input_id": 3, "name": "Detail", "type": "float"},
            {"default": 0.5, "input_id": 4, "name": "Roughness", "type": "float"},
            {"default": 2.0, "input_id": 5, "name": "Lacunarity", "type": "float"},
            {"default": 0.0, "input_id": 6, "name": "Offset", "type": "float"},
            {"default": 1.0, "input_id": 7, "name": "Gain", "type": "float"},
            {"default": 0.0, "input_id": 8, "name": "Distortion", "type": "float"},
        ],
        "outputs": {"Color": {"type": "Color"}, "Fac": {"type": "Fac"}},
        "params": {
            "noise_dimensions": {
                "default": "3D",
                "options": ["1D", "2D", "3D", "4D"],
                "type": "enum",
            },
            "noise_type": {
                "default": "FBM",
                "options": [
                    "MULTIFRACTAL",
                    "RIDGED_MULTIFRACTAL",
                    "HYBRID_MULTIFRACTAL",
                    "FBM",
                    "HETERO_TERRAIN",
                ],
                "type": "enum",
            },
            "normalize": {"default": True, "type": "boolean"},
        },
    },
    "TexVoronoi": {
        "inputs": [
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 0,
                "name": "Vector",
                "type": "vector",
            },
            {"default": 0.0, "input_id": 1, "name": "W", "type": "float"},
            {"default": 5.0, "input_id": 2, "name": "Scale", "type": "float"},
            {"default": 0.0, "input_id": 3, "name": "Detail", "type": "float"},
            {"default": 0.5, "input_id": 4, "name": "Roughness", "type": "float"},
            {"default": 2.0, "input_id": 5, "name": "Lacunarity", "type": "float"},
            {"default": 1.0, "input_id": 6, "name": "Smoothness", "type": "float"},
            {"default": 0.5, "input_id": 7, "name": "Exponent", "type": "float"},
            {"default": 1.0, "input_id": 8, "name": "Randomness", "type": "float"},
        ],
        "outputs": {
            "Color": {"type": "Color"},
            "Distance": {"type": "Distance"},
            "Position": {"type": "Position"},
            "Radius": {"type": "Radius"},
            "W": {"type": "W"},
        },
        "params": {
            "distance": {
                "default": "EUCLIDEAN",
                "options": ["EUCLIDEAN", "MANHATTAN", "CHEBYCHEV", "MINKOWSKI"],
                "type": "enum",
            },
            "feature": {
                "default": "F1",
                "options": [
                    "F1",
                    "F2",
                    "SMOOTH_F1",
                    "DISTANCE_TO_EDGE",
                    "N_SPHERE_RADIUS",
                ],
                "type": "enum",
            },
            "normalize": {"default": False, "type": "boolean"},
            "voronoi_dimensions": {
                "default": "3D",
                "options": ["1D", "2D", "3D", "4D"],
                "type": "enum",
            },
        },
    },
    "TexWave": {
        "inputs": [
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 0,
                "name": "Vector",
                "type": "vector",
            },
            {"default": 5.0, "input_id": 1, "name": "Scale", "type": "float"},
            {"default": 0.0, "input_id": 2, "name": "Distortion", "type": "float"},
            {"default": 2.0, "input_id": 3, "name": "Detail", "type": "float"},
            {"default": 1.0, "input_id": 4, "name": "Detail Scale", "type": "float"},
            {
                "default": 0.5,
                "input_id": 5,
                "name": "Detail Roughness",
                "type": "float",
            },
            {"default": 0.0, "input_id": 6, "name": "Phase Offset", "type": "float"},
        ],
        "outputs": {"Color": {"type": "Color"}, "Fac": {"type": "Fac"}},
        "params": {
            "bands_direction": {
                "default": "X",
                "options": ["X", "Y", "Z", "DIAGONAL"],
                "type": "enum",
            },
            "rings_direction": {
                "default": "X",
                "options": ["X", "Y", "Z", "SPHERICAL"],
                "type": "enum",
            },
            "wave_profile": {
                "default": "SIN",
                "options": ["SIN", "SAW", "TRI"],
                "type": "enum",
            },
            "wave_type": {
                "default": "BANDS",
                "options": ["BANDS", "RINGS"],
                "type": "enum",
            },
        },
    },
    "ValToRGB": {
        "inputs": [{"default": 0.5, "input_id": 0, "name": "Fac", "type": "float"}],
        "outputs": {"Alpha": {"type": "Alpha"}, "Color": {"type": "Color"}},
        "params": {
            "element_0": {"default": 0, "max": 1, "min": 0, "type": "float"},
            "element_1": {"default": 1, "max": 1, "min": 0, "type": "float"},
        },
    },
    "Value": {"inputs": [], "outputs": {"Value": {"type": "Value"}}, "params": {}},
    "VectorMath": {
        "inputs": [
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 0,
                "name": "Vector",
                "type": "vector",
            },
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 1,
                "name": "Vector",
                "type": "vector",
            },
            {
                "default": (0.0, 0.0, 0.0),
                "input_id": 2,
                "name": "Vector",
                "type": "vector",
            },
            {"default": 1.0, "input_id": 3, "name": "Scale", "type": "float"},
        ],
        "outputs": {"Value": {"type": "Value"}, "Vector": {"type": "Vector"}},
        "params": {
            "operation": {
                "default": "ADD",
                "options": [
                    "ADD",
                    "SUBTRACT",
                    "MULTIPLY",
                    "DIVIDE",
                    "MULTIPLY_ADD",
                    "CROSS_PRODUCT",
                    "PROJECT",
                    "REFLECT",
                    "REFRACT",
                    "FACEFORWARD",
                    "DOT_PRODUCT",
                    "DISTANCE",
                    "LENGTH",
                    "SCALE",
                    "NORMALIZE",
                    "ABSOLUTE",
                    "MINIMUM",
                    "MAXIMUM",
                    "FLOOR",
                    "CEIL",
                    "FRACTION",
                    "MODULO",
                    "WRAP",
                    "SNAP",
                    "SINE",
                    "COSINE",
                    "TANGENT",
                ],
                "type": "enum",
            }
        },
    },
}
